import { PT_Serif } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import ToastProvider from "@/components/ToastProvider/ToastProvider";

const ptSerif = PT_Serif({
  subsets: ["latin", "cyrillic"],
  weight: ["400", "700"],
  style: ["normal", "italic"],
  variable: "--font-pt-serif",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body className={ptSerif.variable}>
        <Header />
        {children}
        <ToastProvider />
      </body>
    </html>
  );
}
